# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_manager', '0002_auto_20160528_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallogentry',
            name='call_again',
        ),
        migrations.RemoveField(
            model_name='historicallogentry',
            name='invalid_numbers',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='call_again',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='invalid_numbers',
        ),
        migrations.AddField(
            model_name='historicallogentry',
            name='do_not_call',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='Has the participant asked not to be called again?'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='do_not_call',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='Has the participant asked not to be called again?'),
        ),
        migrations.AlterField(
            model_name='historicallogentry',
            name='call_datetime',
            field=models.DateTimeField(verbose_name='Date of this call'),
        ),
        migrations.AlterField(
            model_name='historicallogentry',
            name='survival_status',
            field=models.CharField(blank=True, choices=[('alive', 'Alive'), ('dead', 'Dead'), ('unknown', 'Unknown')], max_length=10, null=True, verbose_name='Survival status of the participant'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='call_datetime',
            field=models.DateTimeField(verbose_name='Date of this call'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='survival_status',
            field=models.CharField(blank=True, choices=[('alive', 'Alive'), ('dead', 'Dead'), ('unknown', 'Unknown')], max_length=10, null=True, verbose_name='Survival status of the participant'),
        ),
    ]
