# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_manager', '0003_auto_20160529_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallogentry',
            name='do_not_call',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='do_not_call',
        ),
        migrations.AddField(
            model_name='historicallogentry',
            name='call_reason',
            field=models.CharField(choices=[('schedule_appt', 'Schedule an appointment'), ('reminder', 'Remind participant of scheduled appointment'), ('missed_appt', 'Follow-up with participant on missed appointment')], default='schedule_appt', max_length=10, verbose_name='Reason for this call'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicallogentry',
            name='may_call',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, we may continue to contact the participant.'), ('No', 'No, participant has asked NOT to be contacted again.')], default='No', max_length=10, null=True, verbose_name='May we continue to contact the participant?'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='call_reason',
            field=models.CharField(choices=[('schedule_appt', 'Schedule an appointment'), ('reminder', 'Remind participant of scheduled appointment'), ('missed_appt', 'Follow-up with participant on missed appointment')], default='schedule_appt', max_length=10, verbose_name='Reason for this call'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='may_call',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, we may continue to contact the participant.'), ('No', 'No, participant has asked NOT to be contacted again.')], default='No', max_length=10, null=True, verbose_name='May we continue to contact the participant?'),
        ),
    ]
