# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_manager', '0004_auto_20160529_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallogentry',
            name='may_call',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, we may continue to contact the participant.'), ('No', 'No, participant has asked NOT to be contacted again.')], default='Yes', max_length=10, null=True, verbose_name='May we continue to contact the participant?'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='may_call',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, we may continue to contact the participant.'), ('No', 'No, participant has asked NOT to be contacted again.')], default='Yes', max_length=10, null=True, verbose_name='May we continue to contact the participant?'),
        ),
    ]
