# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_manager', '0005_auto_20160529_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallogentry',
            name='call_reason',
            field=models.CharField(choices=[('schedule_appt', 'Schedule an appointment'), ('reminder', 'Remind participant of scheduled appointment'), ('missed_appt', 'Follow-up with participant on missed appointment')], max_length=25, verbose_name='Reason for this call'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='call_reason',
            field=models.CharField(choices=[('schedule_appt', 'Schedule an appointment'), ('reminder', 'Remind participant of scheduled appointment'), ('missed_appt', 'Follow-up with participant on missed appointment')], max_length=25, verbose_name='Reason for this call'),
        ),
    ]
