# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tshipidi_plus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsubjectconsent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Subject Consent'},
        ),
        migrations.AlterModelOptions(
            name='historicalsubjectlocator',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Subject Locator'},
        ),
        migrations.AlterModelOptions(
            name='historicaltshipidisubject',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tshipidi Subject'},
        ),
        migrations.AlterModelOptions(
            name='subjectconsent',
            options={'get_latest_by': 'consent_datetime', 'ordering': ('created',), 'verbose_name': 'Subject Consent'},
        ),
        migrations.AlterModelOptions(
            name='subjectlocator',
            options={'verbose_name': 'Subject Locator'},
        ),
        migrations.AlterModelOptions(
            name='tshipidisubject',
            options={'verbose_name': 'Tshipidi Subject'},
        ),
    ]
